/** 25 legacy Android provider search contracts. Inventory is fixed to upstream 46. */
export const LEGACY_SPECS=Object.freeze({
  "anirena": {
    "host": "https://anirena.com",
    "rows": "table.tl-table > tbody > tr",
    "name": "td.col-name a.tl-torrent-name",
    "size": "td.col-size",
    "seeders": "td.col-se span.tl-se",
    "peers": "td.col-le span.tl-le",
    "magnetSource": "td.col-actions div.tl-actions > a:nth-child(1)",
    "torrentFile": "td.col-actions div.tl-actions > a:nth-child(2)",
    "details": "td.col-name a.tl-torrent-name",
    "resolution": "redirect",
    "pathTemplate": "/?q=MAGNETRA_SEARCH_TOKEN&page=1"
  },
  "audiobookbay": {
    "host": "https://audiobookbay.lu",
    "rows": "div.post",
    "name": "div.postTitle h2 a",
    "details": "div.postTitle h2 a",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/?s=MAGNETRA_SEARCH_TOKEN"
  },
  "bitsearch": {
    "host": "https://bitsearch.to",
    "rows": "div.space-y-4 > div > div:nth-child(1)",
    "name": "h3 a",
    "magnet": "a[href^='magnet:']",
    "torrentFile": "a[href$='.torrent']",
    "details": "h3 a",
    "resolution": "page",
    "pathTemplate": "/search?q=MAGNETRA_SEARCH_TOKEN&page=1&sortBy=seeders"
  },
  "blueroms": {
    "host": "https://www.blueroms.ws",
    "rows": "div.row > div.col-xs-12 > div.card",
    "name": "h4.card-title a",
    "details": "h4.card-title a",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search?g=0&p=0&q=MAGNETRA_SEARCH_TOKEN"
  },
  "bt4g": {
    "host": "https://bt4gprx.com",
    "rows": "div.notion-list-item",
    "name": "div.notion-list-item-title a",
    "details": "div.notion-list-item-title a",
    "size": "div.notion-list-item-meta > span:nth-child(5) b",
    "seeders": "span#seeders",
    "peers": "span#leechers",
    "date": "div.notion-list-item-meta > span:nth-child(2)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search?q=MAGNETRA_SEARCH_TOKEN&category=all&orderby=seeders&p=1"
  },
  "epublibre": {
    "host": "https://epublibre.org",
    "rows": "div.span2",
    "name": "a#stk div.texto-portada h1",
    "details": "a#stk",
    "method": "POST_JSON_HTML",
    "resolution": "page",
    "magnetDetails": "a#en_desc",
    "pathTemplate": "/catalogo/index/0/nuevo/todos/sin/todos/MAGNETRA_SEARCH_TOKEN/ajax"
  },
  "extdotto": {
    "host": "https://ext.to",
    "rows": "table.search-table > tbody > tr",
    "name": "td:nth-child(1) a.torrent-title-link",
    "details": "td:nth-child(1) a.torrent-title-link",
    "size": "td:nth-child(2) span:nth-child(2)",
    "seeders": "td:nth-child(5) span:nth-child(2)",
    "peers": "td:nth-child(6) span:nth-child(2)",
    "date": "td:nth-child(4) span:nth-child(2)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/browse/?q=MAGNETRA_SEARCH_TOKEN"
  },
  "eztvx": {
    "host": "https://eztvx.to",
    "headers": {
      "Cookie": "layout=def_wlinks"
    },
    "rows": "table:last-of-type > tbody > tr",
    "name": "td:nth-child(2) a.epinfo",
    "details": "td:nth-child(2) a.epinfo",
    "magnet": "td:nth-child(3) a.magnet",
    "torrentFile": "td:nth-child(3) a:nth-child(2)",
    "size": "td:nth-child(4)",
    "seeders": "td:nth-child(6)",
    "pathTemplate": "/search/MAGNETRA_SEARCH_TOKEN"
  },
  "filemood": {
    "host": "https://filemood.com",
    "rows": "table > tbody > tr",
    "name": "td.dn-title",
    "details": "td.dn-btn div a",
    "size": "td.dn-size",
    "swarm": "td.dn-status",
    "hashFromDetailsSuffix": true,
    "pathTemplate": "/result?q=MAGNETRA_SEARCH_TOKEN+in%3Atitle"
  },
  "fitgirlrepacks": {
    "host": "https://fitgirl-repacks.site",
    "rows": "article.category-lossless-repack",
    "name": "header h1.entry-title a",
    "details": "header h1.entry-title a",
    "magnet": "a[href^='magnet:']",
    "date": "header div.entry-meta time",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/?s=MAGNETRA_SEARCH_TOKEN"
  },
  "linuxtracker": {
    "host": "https://linuxtracker.org",
    "rows": "table.torrent-table > tbody > tr",
    "name": "td.torrent-name-cell a.torrent-name",
    "details": "td.torrent-name-cell a.torrent-name",
    "size": "td:nth-child(4)",
    "seeders": "td.seeds strong",
    "peers": "td.leeches strong",
    "date": "td:nth-child(3)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/index.php?page=torrents&search=MAGNETRA_SEARCH_TOKEN&category=0&active=0"
  },
  "megapeer": {
    "host": "https://megapeer.vip",
    "rows": "div#index > table > tbody > tr.table_fon",
    "name": "td:nth-child(2) a:nth-child(2)",
    "details": "td:nth-child(2) a:nth-child(2)",
    "torrentFile": "td:nth-child(2) a:nth-child(1)",
    "size": "td:nth-child(3)",
    "seeders": "td:nth-child(4) font:nth-child(2)",
    "peers": "td:nth-child(4) font:nth-child(4)",
    "date": "td:nth-child(1)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/browse.php?search=MAGNETRA_SEARCH_TOKEN&age=&cat=0&stype=0&sort=0&ascdesc=0"
  },
  "mypornclub": {
    "host": "https://myporn.club",
    "rows": "div.torrents_list > div.torrent_element",
    "name": "div.torrent_element_text_div a:nth-child(2) span.torrent_element_text_span",
    "details": "div.torrent_element_text_div a:nth-child(2)",
    "size": "div.torrent_element_info span.teiv:nth-child(4)",
    "seeders": "div.torrent_element_info span.teiv_seeders",
    "peers": "div.torrent_element_info span.teiv_leechers",
    "resolution": "page",
    "magnetDetails": "a.md_btn",
    "pathTemplate": "/s/MAGNETRA_SEARCH_TOKEN/seeders"
  },
  "nonameclub": {
    "host": "https://nnmclub.to",
    "method": "POST_FORM",
    "rows": "table.forumline.tablesorter > tbody > tr",
    "name": "a[href^='viewtopic.php?t='] b",
    "details": "a[href^='viewtopic.php?t=']",
    "torrentFile": "a[href^='download.php?id=']",
    "size": "td:nth-child(6) u",
    "seeders": "td.seedmed b",
    "peers": "td.leechmed b",
    "date": "td:last-child u",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/forum/tracker.php"
  },
  "oxtorrent": {
    "host": "https://oxtorrent.co",
    "rows": "table > tbody > tr",
    "name": "td:nth-child(1) a",
    "details": "td:nth-child(1) a",
    "size": "td:nth-child(2)",
    "seeders": "td:nth-child(3)",
    "peers": "td:nth-child(4)",
    "resolution": "page",
    "magnetDetails": "div.btn-magnet a",
    "pathTemplate": "/recherche/MAGNETRA_SEARCH_TOKEN"
  },
  "therarbag": {
    "host": "https://therarbg.com",
    "rows": "table > tbody > tr.list-entry",
    "name": "td.cellName div a",
    "details": "td.cellName div a",
    "size": "td.sizeCell",
    "seeders": "td:nth-child(7)",
    "peers": "td:nth-child(8)",
    "date": "td:nth-child(4)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/get-posts/keywords:MAGNETRA_SEARCH_TOKEN"
  },
  "1337x": {
    "host": "https://1337x.to",
    "rows": "table.table-list > tbody > tr",
    "name": "td.name a:nth-child(2)",
    "details": "td.name a:nth-child(2)",
    "size": "td.size",
    "seeders": "td.seeds",
    "peers": "td.leeches",
    "date": "td.coll-date",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search/MAGNETRA_SEARCH_TOKEN/1/"
  },
  "tokyotoshokan": {
    "host": "https://tokyotosho.info",
    "rows": "table.listing > tbody > tr",
    "name": "td.desc-top a:nth-child(2)",
    "magnet": "td.desc-top a:nth-child(1)",
    "torrentFile": "td.desc-top a[href$='.torrent']",
    "details": "td.web a:last-child",
    "seeders": "td.stats span:nth-child(1)",
    "peers": "td.stats span:nth-child(2)",
    "size": "td.desc-bot",
    "pathTemplate": "/search.php?terms=MAGNETRA_SEARCH_TOKEN&type=0&searchName=true"
  },
  "torrent9": {
    "host": "https://www6.torrent9.to",
    "rows": "table > tbody > tr",
    "name": "td:nth-child(1) a",
    "details": "td:nth-child(1) a",
    "size": "td:nth-child(3)",
    "seeders": "td:nth-child(4) span.seed_ok",
    "peers": "td:nth-child(5)",
    "date": "td:nth-child(2)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search_torrent/MAGNETRA_SEARCH_TOKEN.html"
  },
  "torrentdatabase": {
    "host": "https://developify.ca",
    "rows": "table.torrent-table > tbody > tr",
    "name": "td:nth-child(1) a:nth-child(2)",
    "magnetHashLink": "td:nth-child(1) a:nth-child(2)",
    "details": "td:nth-child(1) a:nth-child(2)",
    "size": "td.size-cell",
    "seeders": "td:nth-child(5) span:nth-child(1)",
    "peers": "td:nth-child(5) span:nth-child(3)",
    "date": "td.date-cell",
    "pathTemplate": "/search?q=MAGNETRA_SEARCH_TOKEN"
  },
  "torrentdownloads": {
    "host": "https://torrentdownloads.pro",
    "rows": "div.inner_container div.grey_bar3",
    "name": "p:nth-child(1) a:nth-child(2)",
    "details": "p:nth-child(1) a:nth-child(2)",
    "size": "span:nth-child(5)",
    "seeders": "span:nth-child(4)",
    "peers": "span:nth-child(3)",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search/?s_cat=0&search=MAGNETRA_SEARCH_TOKEN"
  },
  "torrentz": {
    "host": "https://torrentz2.nz",
    "rows": "div.results > dl",
    "name": "dt a",
    "details": "dt a",
    "size": "dd span.s",
    "seeders": "dd span.u",
    "peers": "dd span.d",
    "date": "dd span.a span",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/search?q=MAGNETRA_SEARCH_TOKEN"
  },
  "uindex": {
    "host": "https://uindex.org",
    "rows": "table.sr-table > tbody > tr",
    "name": "td.sr-col-name a.sr-torrent-link",
    "details": "td.sr-col-name a.sr-torrent-link",
    "magnet": "td.sr-col-name a.sr-magnet",
    "size": "td.sr-col-size",
    "seeders": "td.sr-col-seeders span.sr-seed",
    "peers": "td.sr-col-leechers span.sr-leech",
    "date": "td.sr-col-uploaded",
    "pathTemplate": "/search.php?search=MAGNETRA_SEARCH_TOKEN&c=0"
  },
  "xxxclub": {
    "host": "https://xxxclub.to",
    "rows": "div.browsetableinside ul > li",
    "name": "span:nth-child(2) a[href^='/torrents/details']",
    "details": "span:nth-child(2) a[href^='/torrents/details']",
    "size": "span.siz",
    "seeders": "span.see",
    "peers": "span.lee",
    "date": "span.adde",
    "resolution": "page",
    "magnetDetails": "a[href^='magnet:']",
    "pathTemplate": "/torrents/search/all/MAGNETRA_SEARCH_TOKEN"
  },
  "0magnet": {
    "host": "https://9mag.net",
    "rows": "table.file-list > tbody > tr",
    "name": "td.result-title a",
    "details": "td.result-title a",
    "size": "td.result-meta div:nth-child(1)",
    "date": "td.result-meta div.result-date",
    "resolution": "input",
    "magnetDetails": "input#input-magnet",
    "pathTemplate": "/search?q=MAGNETRA_SEARCH_TOKEN"
  }
});
export function legacySearchUrl(spec,query){return spec.host+spec.pathTemplate.replaceAll("MAGNETRA_SEARCH_TOKEN",encodeURIComponent(query));}
